services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - ./requirements.txt:/app/requirements.txt
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=chatbot
      - POSTGRES_USER=chatbot_bot
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: