version: '3.3'

services:
  api:
    build: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes


volumes:
  redis_data: